create TABLE person(
  id INTEGER NOT null,
  name VARCHAR(255) NOT NULL ,
  location VARCHAR (255),
  birth_date TIMESTAMP ,
  PRIMARY KEY (id)
);

INSERT INTO PERSON
(ID, NAME,LOCATION,BIRTH_DATE)
VALUES(10001,'ARUN','PHOENIX',SYSDATE());

INSERT INTO PERSON
(ID, NAME,LOCATION,BIRTH_DATE)
VALUES(10002,'ADWITI','PHOENIX',SYSDATE());

INSERT INTO PERSON
(ID, NAME,LOCATION,BIRTH_DATE)
VALUES(10003,'PUSHPA','PHOENIX',SYSDATE());

INSERT INTO PERSON
(ID, NAME,LOCATION,BIRTH_DATE)
VALUES(10004,'PUSHPA','SCOTTSDALE',SYSDATE());